### ISSUE TITLE
Identifying test failures from command-line

### ISSUE THREAD

**Issue by TheAlmightyBob** [pixielabs/cavy-cli#36]
When writing a script to run Cavy tests and notify about test results, it is helpful to know the difference between _test failures_ and _build failures_ (since `cavy-cli` both builds and runs the tests in one go).

Currently it returns `1` in the event of test failures.

My question is: is there confidence that `1` will not also be returned in the event of a build failure (i.e., by the React Native CLI that `cavy-cli` wraps)? Should some more unique number be returned instead?

**Comment by AbigailMcP** [comment]
Hey there!

If there's a build failure, and RN exits with code 1 then cavy will also exit with code 1 (with the message `cavy: react-native exited with code 1`) ... I can see how this is unhelpful!

I'd be happy to make a change to cavy-cli so that it exits with a different code for test failures 👌

I'll hunt around to see whether RN uses any unique codes themselves so that we don't clash in a different way... although I can't remember seeing anything other than the standard codes being used.

**Comment by TheAlmightyBob** [comment]
(a while back I hunted around a little bit and wound up patching `cavy-cli` to return `42`, but you might prefer an error code that's not just a Hitchhiker's reference... and while that seems to have worked thus far, I'm not 100% certain that it won't conflict, I just figured I'd change it again if a conflict was later discovered since it was just a patch... but this seems like it would benefit others, and with the addition of XML reporting I'm hoping to get rid of our patches...)

**Comment by AbigailMcP** [comment]
Addressed in version 2.1.0 https://github.com/pixielabs/cavy-cli/pull/37 :)
